LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'demo'
OUTPUT_DIR: 'experiments/'
NUM_WORKERS: 0
MODEL_CONFIG: 'configs/yamls/model_base.yaml'

TRAIN:
  STAGE: 'stage2'
  CHECKPOINT: 'checkpoints/wham_vit_bedlam_w_3dpw.pth.tar'

MODEL:
  BACKBONE: 'vit'

MMPOSE_CFG:
  POSE_CONFIG: 'configs/VIT/vipnas_mbv3_coco_256x192.py'
  POSE_CHECKPOINT: 'checkpoints/vipnas_mbv3_coco_256x192-7018731a_20211122.pth'
  DET_CONFIG: ''
  DET_CHECKPOINT: 'checkpoints/yolov8m.pt'
  BBOX_CONF: 0.5
  TRACKING_THR: 0.1
  MINIMUM_FRMAES: 30

DPVO:
  CFG: 'configs/DPVO/default.yaml'
  CKPT: 'checkpoints/dpvo.pth'
